import { Home } from './home';
import { Notifications } from './notifications';
import { Settings } from './settings';
import { Arrow } from './Arrow';
import { Basket } from './basket';
import { Facebook } from './facebook';
import { Instagram } from './instagram';
import { WhatsApp } from './WhatsApp';
import { Logo } from './logo';
export { Home, Notifications, Settings, Arrow, Basket, Instagram, Facebook, WhatsApp, Logo };
